alphagov/pay-products-ui

- app/paths.js
- test/unit/client/product_client/payment/create_test.js
- test/unit/client/product_client/payment/get_by_payment_external_id_test.js
- test/unit/client/product_client/payment/get_by_product_external_id_test.js
- updated `/success` to `/successful` as per design
- updated Pact `after` statements to include `Promise.catch` calls
> PP-2727 Update success URL and add catches to pact setup in tests

- Jenkinsfile
This will trigger e2e tests tagged with `e2e-products`
Dropping `-` from tag name due to bash variable names not supporting `-`s. For tagging we are already not using it in pay-scripts. So using the same convention
> PP-2855 add end to end test step

- Dockerfile
- docker/build_and_test.Dockerfile
- Use symlink rather than directory copy for node_modules caching layer in dockerfiles
- Bumped node-alpine image to 6.12.0 
- Speeds up the docker image build process both for the test image and the deploy image
- Makes the images smaller too
- Includes some minor security fixes, should also upgrade alpine base layer.
> PP-2851 bump node to 6.12.0 

- Jenkinsfile
Moving away from having required to declare specific maven profiles for various category of end2end builds. `end2end-tagged` profile is generic enough to run any kind of test groups with necessary includes and excludes. This moves the products to use the `end2end-tagged` profile.
> PP-2923 migrating to end2end-tagged maven test profile

- package.json
There is a security issue reported by Snyk about serve-favicon@2.4.3. Recommended fix is to upgrade to serve-favicon@2.4.5.
- https://snyk.io/test/npm/serve-favicon/2.4.3?severity=high&severity=medium&severity=low
> PP-2997 Regular Expression Denial of Service security issue of servefavicon

- Jenkinsfile
This needs to be done until we fully migrate over to AWS.
At the same time remove the ansiColor trigger which is disabled in jenkins
> PP-2996 Trigger products to deploy both on PaaS as well as AWS

- app/assets/sass/template/header.scss
- app/controllers/demo_payment/payment_success_controller.js
- app/middleware/resolve_payment.js
- app/middleware/resolve_product.js
- app/models/Product.class.js
- app/utils/proxy.js
- app/views/includes/propositional_navigation.njk
- app/views/layout.njk
- docker/build_and_test.Dockerfile
- package.json
- test/unit/middleware/resolve_payment_test.js
- test/unit/middleware/resolve_product_test.js
- adds `serviceName` to `Product` class
- adds `product` and `payment` to `res.locals`
- adds `product.serviceName` to proposition header
- moves nyc to separate `npm run test-with-coverage`
- removes unneeded console.logs from `proxy.js`
> PP-3035 Add product.serviceName to nav

- Jenkinsfile
As it is already tagged after PaaS deployment.
> PP-2996 avoid tagging after AWS deployment

- app/models/Payment.class.js
- app/services/clients/products_client.js
- test/fixtures/product_fixtures.js
- test/unit/client/product_client/payment/create_test.js
create payment allows overriding with a different price (optional). If not provided it will default to product price
> PP-3034 enable price override

- Jenkinsfile
We are no longer in PaaS so removing this step.
Also made deploy job to tag after deployment.
> PP-3204 remove paas deployment

- app/assets/sass/application.scss
- app/assets/sass/modules/_flash.scss
- app/controllers/adhoc_payment/get_amount_controller.js
- app/controllers/adhoc_payment/submit_amount_controller.js
- app/views/includes/flash.njk
- app/views/layout.njk
- server.js
- test/unit/controllers/adhoc_payment/submit_amount_controller_test.js
Hacky fix. Its seems `connect-flash` only works well when `req.flash` followed by a `res.redirect()`. so here making explicit flash message on output data to trigger the error message display.
> PP-3034 Fix for not displaying the flash error messages

- app/utils/custom_certificate.js
We have made some changes to certs dir on boxes, which means it may
contain sub dirs. The loader as is broke if it encounter a sub dir.
This fixes that.
> PP-3252 Make certsloader more tolerant

- Dockerfile
- docker/build_and_test.Dockerfile
Use the GOV.UK Pay Node Base Image, because: 
1) its consistent 
2) its safer 
3) it has chamber in it meaning we can continue the process of ECSification.
> PP-3252 Use pay base image 

- npm-shrinkwrap.json
- package.json
Remove `forever` from dependencies. We don't need `forever` when running in Amazon EC2 Container Service.
`forever@0.15.3` depends on `timespan` which has "Regular Expression Denial of Service (ReDoS)" vulnerability: https://snyk.io/vuln/npm:timespan:20170907
> PP-3401 Update dependencies part 2

- app/services/clients/products_client.js
- test/unit/client/product_client/product/get_by_gateway_account_id_test.js
Updated `product-client` following to API breaking change in `pay-products`.
While retrieving all products by gateway account, the gateway account is now provided on the resource path instead of as a query param.
> PP-3441 Updated `product-client` following to API breaking change

- app/controllers/friendly_url_redirect_controller.js
- app/paths.js
- app/routes.js
- app/services/clients/products_client.js
- test/fixtures/product_fixtures.js
- test/unit/client/product_client/product/get_by_product_path_test.js
- test/unit/controllers/adhoc_payment/post_index_controller_test.js
- test/unit/controllers/friendly_url_redirect_controller_test.js
* New method in product client that offers the ability to retrieve a product by product path. The payload of the product response has also been updated to handle the additional friendly url link.
* New controller that handles a `friendly URL` by retrieving the product associated to the `service name path` and `product name path` and redirecting to the `pay URL`.
> PP-3308 Redirect friendly url

- app/views/adhoc-payment/index.njk
Linebreaks were not showing as nunjucks strips them out by default, this
is good most of the time. So in this case we can use nunjucks filters to
show. If we convert the \n breaks to `<br>'s` and then escape we can see
them. Because escaping is dangerous we also strip out all tags so there
is nothing dodgy left to escape.
> PP-3510 - display description line breaks

- app/views/layout.njk
On other user facing pages we don’t show “Pay” or the beta tag
> PP-3600 - remove beta tag and Pay from Header

- app/views/includes/footer-support-links.njk
- app/views/layout.njk
The template was copied from the product page when it should match the
one on pay-frontend. This updates the links
> BAU - fix broken logo link and remove links from footer

- app/browsered/field-validation-checks.js
- app/controllers/pre_payment_controller.js
- app/controllers/product_reference/get_product_reference_controller.js
- app/controllers/product_reference/index.js
- app/controllers/product_reference/post_product_reference_controller.js
- app/models/Product.class.js
- app/paths.js
- app/routes.js
- app/views/reference/index.njk
- test/fixtures/product_fixtures.js
- test/unit/controllers/payment_reference/get_product_reference_controller_test.js
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
- test/unit/controllers/pre_payment_controller_test.js
- Updated pre-payment controller to handle ADHOC payments with reference
enabled
- Added GET controller to handle rendering the page with the input field
- Added POST controller to handle form validation for the input field and
to forward to the payment amount page
- Added the new route to paths and exposed the http methods in the router
- Updated Product class to cater for the new properties: `reference_enabled`,
`reference_label` and `reference_hint`
- Added a new view that holds the form for the input field
- Updated tests and product fixtures to have the new properties
> PP-3726 Add extra page for reference input

- app/controllers/adhoc_payment/get_index_controller.js
- app/controllers/adhoc_payment/post_index_controller.js
- app/controllers/make_payment_controller.js
- app/controllers/product_reference/get_product_reference_controller.js
- app/services/clients/products_client.js
- app/views/adhoc-payment/index.njk
- app/views/reference/index.njk
- test/unit/controllers/adhoc_payment/get_index_controller_test.js
- test/unit/controllers/adhoc_payment/get_index_controller_unit_test.js
- Added field payment_reference to the client call to `products`
- Updated views to pre-populate the reference when on reference page
and to have it hidden on the payment page
- Updated controllers to handle redirection when payment reference
required and not set
> PP-3726 Wire up reference field

- app/controllers/adhoc_payment/get_index_controller.js
- app/controllers/adhoc_payment/post_index_controller.js
- app/controllers/product_reference/get_product_reference_controller.js
- app/controllers/product_reference/post_product_reference_controller.js
- app/utils/cookie.js
- app/views/adhoc-payment/index.njk
- app/views/reference/index.njk
- test/test.env
- test/unit/client/product_client/payment/create_test.js
- test/unit/controllers/adhoc_payment/get_index_controller_unit_test.js
- test/unit/controllers/payment_reference/get_product_reference_controller_test.js
- test/unit/utils/cookie_test.js
- Moved reference value to the session such that is available to pre-populate
the input field when navigating back to the page, after adding a session
reference
- Removed reference hidden field from payment amount page because now
the value is in session
- Added extra methods to set/get values from session
- Added unit test for adhoc controller as this controller can be 3rd down
the line in the call chain and cannot be accessed from a direct route
- Modified adhoc controller to check for reference set in session, as opposed
to request or hidden field
- Updated test for client to create a payment with amount and reference
- Added unit tests for cookies
- Added naxsi validation on reference field if pre-populated
> PP-3726 Handle edge cases for reference enabled

- app/utils/cookie.js
- server.js
Environment variable flags to permit setting of secure cookies on http and to omit appmetrics module. These are necessary changes in order to add products-ui to the pay local cli tool. Similar changes exist selfservice.
@tlwr
> Add environment variable flags

- app/controllers/adhoc_payment/post_index_controller.js
- test/unit/controllers/adhoc_payment/post_index_controller_test.js
Without this fix, we convert £9.95 to 994p, which is just 😬
> Fix rounding error when converting input like 9.95 (£) to 995 (p)

- Dockerfile
Update to Alpine Linux 3.8.1 and bring in Nodejs 8.11.4
CI will save us
> PP-4344: Update to our Alpine 3.8.1 w/nodejs 8.11.4 base image

- server.js
Higher priority lint warnings flagged and resolved. Boolean equality
check on a string will always return false if defined resulting in a
different logical progression than expected.
Related to https://github.com/alphagov/pay-selfservice/pull/1041
> PP-4564: Address priority repo lint issues

- app/views/includes/head.njk
- app/views/layout.njk
Noticed that our templates include IE8 boilerplate stuff that doesn’t work
We don’t technically support IE8 anyway, so rather than fix I will just remove all together.
> PP-4972 - remove unused ie8 boilerplate stuff

- app/middleware/resolve-language.js
- app/models/Product.class.js
- config/i18n.js
- locales/cy.json
Add a Welsh language file. This is missing some translations, but these will be added in by PP-5006 before Welsh payment links are made publicly available.
Add the language property to product model and make sure the language file to use is resolved.
> PP-5005 Resolve language from product

- package.json
- test/unit/client/adminusers_client/find_service_test.js
- test/unit/client/product_client/payment/create_test.js
- test/unit/client/product_client/payment/get_by_gateway_account_id_and_reference_test.js
- test/unit/client/product_client/payment/get_by_payment_external_id_test.js
- test/unit/client/product_client/payment/get_by_product_external_id_test.js
- test/unit/client/product_client/product/create_test.js
- test/unit/client/product_client/product/delete_test.js
- test/unit/client/product_client/product/disable_test.js
- test/unit/client/product_client/product/get_by_gateway_account_id_test.js
- test/unit/client/product_client/product/get_by_product_external_id_test.js
- test/unit/client/product_client/product/get_by_product_path_test.js
Fix 'done' being called immediately in "after" step in pact tests and
instead return the Promise to ensure it is resolved.
Fix duplicate pact descriptions.
> PP-5005 Fix existing pact tests

- app/views/adhoc-payment/index.njk
- app/views/error.njk
- app/views/pay/confirmation.njk
- app/views/pay/failed.njk
- app/views/reference/index.njk
- config/pay-translation.js
- server.js
Sister of this PR https://github.com/alphagov/pay-frontend/pull/752
i18n’s built in translation function __() returns the key
if it can’t find a translation. This is problematic as we show
something gross like 'cardDetails.title' to the user.
So this is a custom function that will check that the string
doesn’t equal the key. And if it does throw an error so the
template fails to render but with a nice helpful error message.
The error looks like this:
Which is how all the other Nunjucks errors look and it would mean you could never get your PR through tests
> PP-5015 throw error for missing translation

- test/fixtures/product_fixtures.js
- test/unit/client/product_client/product/get_by_gateway_account_id_test.js
- test/unit/client/product_client/product/get_by_product_external_id_test.js
- test/unit/client/product_client/product/get_by_product_path_test.js
- Modify pacts to expect the new 'language' field.
- Change consumer of pact tests for products endpoints to 'products-ui' so they will be run.
- Add provider states to tests that require them.
- Modify Pact tests to get them working against the provider.
- Remove a Pact test which was wrong and unnecessary to test products by gateway account when there are no products.
> PP-5005 Enable products pact tests

- Jenkinsfile
- test/unit/client/adminusers_client/find_service_test.js
- Change consumer of generated pacts so they are published to the pact broker.
- Fix pact tests so they pass against adminusers.
- Run adminusers contract tests as part of build.
- Add environment variable to run with Java 11, as adminusers now uses Java 11
> PP-5007 Enable adminusers pact tests

- app/controllers/friendly_url_redirect_controller.js
- app/controllers/make_payment_controller.js
- app/controllers/payment_complete_controller.js
- app/controllers/pre_payment_controller.js
- app/middleware/csrf.js
- app/middleware/resolve_payment_and_product.js
- app/middleware/resolve_product.js
- app/utils/response.js
- app/views/error.njk
- locales/cy.json
- locales/en.json
- test/unit/controllers/friendly_url_redirect_controller_test.js
- test/unit/controllers/payment_complete_controller_test.js
- test/unit/controllers/pre_payment_controller_test.js
- test/unit/middleware/resolve_payment_and_product_test.js
- test/unit/middleware/resolve_product_test.js
PP-5006 - Move error messages to strings file
> Also add missing Welsh translations and make all apostrophes proper
PP-5006 - Remove all error message strings
> And replace with path to string in locales/*.json
> Also use object destructuring for requires
PP-5006 - Update tests with new strings
> PP-5006 - make errors translatable

- app/controllers/adhoc_payment/post_index_controller.js
- app/controllers/product_reference/post_product_reference_controller.js
- locales/cy.json
- locales/en.json
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
- Internationalise server-side errors for the reference page.
- Add server-side check for disallowed characters.
- Use the res.locals.__p in controllers rather than initialising i18n each time.
> PP-4986 Internationalise reference server validation

- app/controllers/adhoc_payment/post_index_controller.js
We were storing in a cookie the value users enter in the reference
field for as long as the cookie persists. This means if you made a
payment link payment and then came back a few days later to do it again
it would show you the reference from the last time, people find the
disconcerting and it’s probably not very useful.
So now when the user is passed from product-ui to frontend the stored
reference is cleared.
> PP-5314 - Clear stored reference when passing user to frontend

- app/views/adhoc-payment/index.njk
The Design System team have done some accessibility testing on `input
type="number"` and deemed them problematic. They have suggested using
`input type="text" inputmode="numeric" pattern="[0-9]*"`
instead as documented here https://github.com/alphagov/govuk-frontend/issues/1449
But because this is a currency input and we need to accept decimals points we’re going with 
`input type="text" inputmode="numeric"` in this case
> PP-5366 - use inputmode on numeric fields

- test/fixtures/product_fixtures.js
Randomly generated values put in the pacts were causing pact broker to think the pact has changed each commit, forcing us to have to redeploy in order to verify the "new" pacts. Remove this randomisation to fix this.
> BAU Fix randomised values in pacts

- app/views/adhoc-payment/index.njk
- app/views/reference/index.njk
Before the titles were just the service name. Now they follow the
following pattern
What the page does - Product name - Service name
> PP-5574 - Add more informative page titles

- app/utils/logger.js
- app/utils/sentry.js
- package-lock.json
- package.json
- server.js
Send error level log messages to Sentry. Using the log level to
control when messages are sent to Sentry seems intuitive and since we now
require a common logger throughout the application it offers a
convenient point to add Sentry.
Unhandled exceptions will be caught by the Sentry error middleware added
within server.js as per the guidlines when using Sentry with Express.
When initialising Sentry a beforeSend filter is added to remove the
request element from the event if it exists. The request element contains the
data from a failed request and this can include sensitive information such
as card numbers. We may want to introduce more refined filtering to allow
non-sensitive information from a failed request to go to Sentry at a
later date.
app/utils/sentry.js and more elements of …
> PP-5756 Add Sentry

- app/middleware/logging_middleware.js
- server.js
The middleware uses morgan to log requests in a JSON format using a
format function from pay-java-commons which produces a log line as a
JSON string.
We then parse this as JSON and give it to our custom logger, which uses
winston to produce a structured log message which also includes all the
global keys we log for all lines.
> PP-5775 Add middleware to log requests in JSON format

- app/utils/logger.js
- test/test_helpers/supress-logs.js
Add an 'environment' field to the logs, so that it is possible to filter
by environment using a Splunk text search. Splunk does currently extract
the environment from the source if it is explicitly searched on using
e.g. the term 'environment="production-2"', but some of our reports use
a text search so will not pick up on all log lines.
The text search continues to work for many logs where the environment is
included in some way in the log message, but not for others where it
isn't so it makes sense to get rid of this ambiguity.
In the apps producing the logs, we get the environment from an
environment variable which is already configured for use by Sentry.
> PP-5777 Add environment field to logs

- app/utils/request_logger.js
Requests to other apps returning failure codes does not necessarily
mean an error, so don't log at error level.
> PP-5809 Don't log request failures at error level

- app/middleware/error_handler.js
- app/utils/request_logger.js
- app/utils/response.js
These dashes were there previously because before we logged in JSON the
logger would concatenate the JSON object it was passed as a second
parameter into the line.
Now, however, the keys in this JSON object are merged into the top-level
JSON object for the logline, so there is a hanging dash on the end of
the message which makes it appear that the message is incomplete. Remove
these.
> PP-5809 Remove trailing dashes in log lines

- app/utils/response.js
We were logging a line at error level whenever an error page was displayed, but we display the error page for events such as a payment link not being found.
Only log an error if the status code is 500, not for other statuses.
Also move information in the log line into structured key/values.
> PP-5809 Don't log error when error page shown for non-500 errors

- app/views/adhoc-payment/index.njk
- locales/cy.json
- locales/en.json
* we do not have control of the payment link name entered by services
* don't include this in the page title sent to google analytics - this breaks PII
* make the title more meaningful 
> "Make a payment to Steven's service"
> PP-5918 Remove payment link name from title (PII)

- app/views/reference/index.njk
Follows up on https://github.com/alphagov/pay-products-ui/pull/583, reference is also in the landing page title. 
* Make this title the same as "entering amount page"
> PP-5918 Remove reference from landing page (PII)

- package.json
- Reverts the version of Sentry we use to see if this fixes errors
> BAU Revert Sentry Version Bump

- app/middleware/logging_middleware.js
Logging middleware was throwing an error when attempting to log, as
`logging.requestLogFormat` in pay-js-commons had been modified, but
the consuming module hadn't been updated to work with the changes.
> BAU Fix request logging

- app/views/includes/head.njk
Complying with ICO guidance around cookie consent we can't set
non-essential cookies without consent being granted. In the short term
then we have to disable Google Analytics as it stores cookies.
> PP-5977 Disable google analytics

- dev.yml
- manifest.yml
- package.json
I've added a `manifest.yml` and `dev.yml` for pushing the app to PaaS.
The app can be pushed as follows:
```
cf push --vars-file dev.yml \
--var adminusers_url=https://adminusers.example.com \
--var products_url=https://products.example.com \
--var selfservice_transactions_url=https://selfservice.example.com \
--var products_ui_route=pay-products-ui-test.cloudapps.digital
```
The `public/.keep` has been added because Express complains about
a missing `public` directory if it doesn't exist and the PaaS app fails
to start.
> PP-6029: Add PaaS manifest

- package.json
PaaS node buildpack no longer supports 12.11.1. To avoid having to keep
bumping the engine version whilst maintaining compatibility with our
existing docker image build process, this pins the major version whilst
accepting minor and pataches releases greater than 12.11.1.
> PP-6031 bump engines version to 12.14.1

- env-map.yml
- manifest.yml
Add a build pack that extracts values from within VCAP_SERVICES which is
where the credentials from bound services will be provided to the app
running on PaaS. Using this buildpack means we do not need to alter how
our app works, but rather provide a mapping from the VCAP_SERVICES var to its
current name.
Tested that the env var are correctly set. `selfservice_transactions_url` is null becaues the .tf update hasn't been run yet see https://github.com/alphagov/pay-omnibus/pull/70/files
```
GDS5062 > cf ssh products-ui -c "/tmp/lifecycle/shell /home/vcap/app 'env | sort'" | grep URL
ADMINUSERS_URL=http://adminusers-stg.apps.internal:8080
PRODUCTS_URL=http://products-stg.apps.internal:8080
SELFSERVICE_TRANSACTIONS_URL=null
```
> PP-6085 Add env-map buildpack

- env-map.yml
- manifest.yml
Env vars which are specific to products-ui and differ by environment
are to be provided via the products-ui-secret-service. The mapping
between these vars and their keys within the vars returned by
products-ui-secret-service are defined within env-map.yml.
Tested by manually pushing to staging after adding the secret-service. App runs and vars are present.
> PP-6127 Add secret service for PaaS

- app/controllers/product_reference/post_product_reference_controller.js
- app/views/reference/index.njk
- locales/cy.json
- locales/en.json
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
Current validation on payment link reference doesn't make sense, there
is both client and server side validation (with useful error messages)
for some validation -- there appears to be no client side validation for
length; the `max-length` HTML attribute is used which won't allow the
user to enter something too long but will also not give any meaningful
feedback (instead just truncating whatever is entered).
* Remove max length assertion - allow the server side
validation to provide the user with a meaningful message
* Reduce the max length to 50, the Products database stores this in
`reference_number` which is currently restricted to `VARCHAR(50)`
https://github.com/alphagov/pay-products/blob/master/src/main/resources/migrations/00029_alter_column_reference_number_length_payments.sql#L4 …
> PP-5984 Fix validation parity on user entered reference

- package-lock.json
- package.json
- Bump `pay-js-commons` from 2.24.0 -> 2.25.0
> BAU Bump pay-js-commons

- env-map.yml
- manifest.yml
Set the METRICS_HOST and METRICS_PORT from the app-catalog to send
metrics to the carbon-relay app.
> PP-6254 Add carbon-relay

- package-lock.json
- package.json
- Also minor bumps to Chokidor & yargs_parser
> BAU Bump JS commons to 2.29.0

- app/views/includes/head.njk
Add `<meta name="robots" content="noindex, nofollow">` to all payment link, prototype and demo payment pages so search engines don’t index them.
This is the approach specified by:
https://www.gov.uk/service-manual/technology/get-a-domain-name#telling-search-engines-not-to-index-pages
> PP-6869 Tell search engines not to index card payment pages

- app/assets/robots.txt
https://www.gov.uk/service-manual/technology/get-a-domain-name#telling-search-engines-not-to-index-pages says to use `<meta name="robots" content="noindex, nofollow">` to tell search engines not to index our pages. Additionally, it says not to use `robots.txt` to prevent crawling because this stops the `noindex` directive from being seen by search engines.
We added `<meta name="robots" content="noindex, nofollow">` in commit 38f1430d901f0c85ee1c6669c4a97babc818d45d. This commit completes the work by removing the `robots.txt` file.
> PP-6869 Remove robots.txt file

- app/controllers/product_reference/post_product_reference_controller.js
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
Sending a payment reference of just white space characters to Publicapi
to create a payment will return an error `Missing mandatory attribute:
reference`. Add a check to the payment reference to ensure it is not
only white space characters.
At present its possible to enter `"    "` in the reference field and go through create payment which then displays
```
An error occurred:
Sorry, we’re unable to process your request. Try again later.
```
This was caught but this Sentry error: https://sentry.io/organizations/govuk-pay/issues/1980313985/?project=5480169&referrer=slack
You can test this behaviour with a simple test to publicapi
```
{
"amount": 10,
"reference": "       ",
"description": "testing this out",
"return_url": "https://www.google.com"
}
{
"field": "reference",
"code": "P0101", …
```
> PP-7324 Check for payment reference that are just white space

- .secrets.baseline
- README.md
- app/controllers/make_payment_controller.js
- app/controllers/payment_complete_controller.js
- app/controllers/payment_status_controller.js
- app/controllers/pre_payment_controller.js
- app/routes.js
- app/views/pay/confirmation.njk
- config/index.js
- locales/cy.json
- locales/en.json
- test/test.env
- test/unit/controllers/payment_complete_controller_test.js
- test/unit/controllers/pre_payment_controller_test.js
Add support for `AGENT_INITIATED_MOTO` payments. These present the same user journey as `ADHOC` payments but with some changes to the confirmation page.
> PP-7698 Add support for AGENT_INITATED_MOTO payments

- package-lock.json
- package.json
This will pick up the latest custom branding changes. Note that `3.1.0`
was created some time ago in error, this is not downgrading
pay-js-commons, version `3.0.8` is the latest.
> ZD_4487202 Bump pay-js-commons

- README.md
- app/routes.js
Make `/.well-known/security.txt` and `/security.txt` redirect to https://vdp.cabinetoffice.gov.uk/.well-known/security.txt.
Update `README.md` to reference the Cabinet Office CDIO Cyber Security vulnerability disclosure policy and security.txt file rather than the GOV.UK Pay security vulnerability email address.
> PP-8095 Add security.txt file

- app/browsered/field-validation-checks.js
- app/controllers/product-reference/get-product-reference.controller.js
- app/controllers/product-reference/post-product-reference.controller.js
- app/views/reference/index.njk
- locales/cy.json
- locales/en.json
- package-lock.json
- package.json
- test/unit/browsered/field-validation-checks.test.js
- test/unit/controllers/payment-reference/post-product-reference.controller.test.js
- Checks reference entered for a potential PAN and asks users for confirmation
- only numbers (with special characters '-' and space) are considered
- and reference number of length between 12 and 19 digits excluding special characters (card number lengths across brands) are checked for potential PAN
- Adds new library luhn-js to check reference for potential PAN using luhn algorithm
**_Note:_ Content still to be finalised**
**Confirmation page**
**on edit, takes back to reference page**
> PP-8300 Confirm reference if found to be a potential PAN

- app/utils/captcha.js
- app/views/adhoc-payment/index.njk
- server.js
- test/test.env
Enterprise and basic Google reCAPTHCA target different validation
endpoints (either hosted by enterprise or the standard api for basic)
and load different widgets.
Allow environments to set these.
> PP-8551 Set google reCATPCHA URLs with environments

- app/utils/captcha.js
- app/views/adhoc-payment/index.njk
- server.js
- test/test.env
- test/unit/utils/captcha.test.js
The enterprise version of captcha expects a different interaction:
* POST body JSON instead of xhtml/form data
* secret key passed in through `?key=` paraemeter to endpoint
* returns a likelihood score rather than a simple pass/ fail response
* assesment passed as an `event` instead of a one off token
Fork the existing method to make these changes and decide whether to use
basic or enteprise with an environment flag.
> PP-8688 Add support for captcha enterprise version

- package-lock.json
- package.json
Reverts alphagov/pay-products-ui#1414
[Build](https://build.ci.pymnt.uk/job/pay-products-ui/job/master/150/console) fails with 
```
12:23:28  (node:72) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
12:23:28  (node:72) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
12:23:28      at Function.keys (<anonymous>)
12:23:28      at Object.help (/app/node_modules/mocha/node_modules/yargs/lib/usage.js:240:22)
12:23:28      at Object.self.showHelp (/app/node_modules/mocha/node_modules/yargs/lib/usage.js:432:15)
12:23:28      at Array.<anonymous> (/app/node_modules/mocha/lib/cli/cli.js:53:13)
12:23:28      at Object.fail …
```
> Revert "Bump envfile from 5.2.0 to 6.17.0"

- Dockerfile
Faster, too: 51s with `npm install`, 41s with `npm ci`
> PP-8901 Use npm ci in dockerfiles

- app/paths.js
- app/payment-link-v2/amount/get-index.controller.js
- app/payment-link-v2/amount/post-index.controller.js
- app/payment-link-v2/amount/post-index.controller.test.js
- app/payment-link-v2/reference/get-back-link-url.js
- app/payment-link-v2/reference/get-back-link-url.test.js
- app/payment-link-v2/reference/get-index.controller.js
- app/payment-link-v2/reference/get-index.controller.test.js
- app/payment-link-v2/reference/index.js
- app/payment-link-v2/reference/is-a-potential-pan.js
- app/payment-link-v2/reference/is-a-potential-pan.test.js
- app/payment-link-v2/reference/post-index.controller.js
- app/payment-link-v2/reference/post-index.controller.test.js
- app/payment-link-v2/reference/reference.njk
- app/routes.js
- app/utils/validation/form-validations.js
- app/utils/validation/form-validations.test.js
- locales/cy.json
- locales/en.json
- Add new code for the new Payment Links reference page:
- Add new controllers.
- Add new Nunjucks page.
- Add new form validations.
- Create new `get-back-link` function - works out the back link for the reference page.
- If the reference is a potential PAN number, then redirect to the `reference/confirm`
- Extract the `isAPotentialPanNumber` function into it's own function.
> PP-8940 New payments link - reference page

- app/payment-link-v2/amount/get-index.controller.test.js
- app/payment-link-v2/amount/post-index.controller.test.js
- app/payment-link-v2/reference/get-index.controller.test.js
- app/payment-link-v2/reference/post-index.controller.test.js
- In the tests, when we use `sinon.assert.called` and then call `sinon.assert.calledWith`.
- It is unnecessary to use `sinon.assert.called`.
- As the `sinon.assert.callendWith` does everything that method does as well
as check the params.
- So remove all instances of `sinon.assers.called`
> PP-8940 Clean up tests for new reference and amount pages

- app/payment-link-v2/amount/amount.controller.js
- app/payment-link-v2/amount/amount.controller.test.js
- app/payment-link-v2/reference/reference.controller.js
- app/payment-link-v2/reference/reference.controller.test.js
- app/payment-link-v2/reference/reference.njk
- locales/cy.json
- locales/en.json
- Update to show `Payment link` name in the header.
- When showing Reference page errors - make sure to reference label
- Capitlise the letter of the reference page errors in the code
- Easier to do it here rather then CSS, as the Design System `error summary`
does not allow us to add CSS classes to the individual errors.
- Mobile view - make the input span the entire screen.
- Fix rounding errors when retrieving and displaying the `amount` from the session.
- Fix bugs with saving the amount and reference number to the session
with the wrong variable names.
> PP-8940 Reference Page - Fixes as per code review comments

- cypress.json
- package-lock.json
- package.json
- test/cypress/plugins/index.js
- test/cypress/support/index.js
- test/cypress/test.env
PP-8970 Cypress - initial setup
- Add config files for setting up Cypress.
- Most of this was taken from Self service and modified.
- Updated the package.json: 
- Added the new Cypress dependencies:
- Cypress
- Mountebank
- request-promise-native
- Add the Cypress run scripts.
> PP-8970 Cypress - initial setup

- app/payment-link-v2/reference/reference.njk
- app/views/macros/error-summary.njk
- locales/cy.json
- locales/en.json
- package.json
- test/cypress/integration/reference-page/reference.cy.test.js
- Add new Cypress test for the Reference page
- Add HTML 'data-cy' attributes - as per Cypress recommendations.
- These values are used in Cypress tests to select the elements.
- Update locale files so `|` is shown correctly.
> PP-8970 Adding Cypress test for Reference page + general Cypress cleanup

- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/confirm/confirm.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/confirm/confirm.cy.test.js
- Update controller with `getPage` function - to pass data required for the confirm page.
- Saves the data to show in the `Summary list` table as an array.
- Update confirm page to show required data.
- Display the data using the Design System `summary list` component.
required by the macro.
- Add Unit tests.
- Create new Cypress test.
> PP-8942 Confirm page - update page.

- .github/workflows/post-merge.yml
- .github/workflows/run-tests.yml
1. Use post-merge.yml pattern for post-merge (calling run-tests as a reusable workflow, and don't run run-tests on PRs itself).
2. Cache pacts directory from unit tests
3. Publish consumer pact tests
4. Run provider pact tests for adminusers and products
Prior to removing the on pr on post-merge this run completed:
https://github.com/alphagov/pay-products-ui/actions/runs/1986201320
> PP-9239: post merge tests in gha

- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/confirm/confirm.njk
- app/routes.js
- locales/cy.json
- locales/en.json
- Add POST route for the `confirm` page.
- Add code to handle Recaptcha functionality.
- Update `confirm` nunjuks file.
- Add tests.
- Will add the `success` test once the payment code is in place.
- Refactor code - to move the summaryElements code to a new method -
getSummaryElements()
- So it can be used for both the GET and POST methods.
> PP-8942 Confirm page - Add recaptcha

- app/middleware/error-handler.js
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/views/404.njk
- app/views/500.njk
- locales/cy.json
- locales/en.json
- Update `confirm.controller.js` - to add code to create
payment.
- Uses the `productClient` to create a charge.
- Redirect the user to the charge > next.url.
- If the call to `products client > create payment` fails - redirect to a
a new 500 page.
- Add unit tests.
> PP-8942 Confirm page - add payment code

- app/controllers/pre-payment.controller.js
- app/controllers/pre-payment.controller.test.js
- app/payment-link-v2/utils/payment-link-session.js
- app/payment-link-v2/utils/payment-link-session.test.js
- app/utils/cookie.js
- bin/publish-pacts.js
- test/cypress/integration/payment-link-v2/start.cy.test.js
We want to index the session for payment links by the product external id. This is because there is an existing issue that can cause the session to be interfered with if 2 payment links are opened in different browser tabs and completed alongside each other.
If a payment link is abandoned, the cookie will also remain in the users browser for next time they try to complete a payment link if it has not expired.
Indexing the session by product external ID will ensure at least that a session cookie remaining from filling in one payment link is not picked up by a user attempting to complete a completely different payment link which will more than likely require a different reference and amount.
These utility methods are intended to be used whenever we read/write from the payment link session.
> PP-8982 Add payment link session utilities

- app/payment-link-v2/amount/amount.controller.js
- app/payment-link-v2/amount/amount.controller.test.js
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/reference-confirm/reference-confirm.controller.js
- app/payment-link-v2/reference-confirm/reference-confirm.controller.test.js
- app/payment-link-v2/reference/reference.controller.js
- app/payment-link-v2/reference/reference.controller.test.js
- app/payment-link-v2/utils/payment-link-session.js
Wherever we get or set the reference or amount on the session, replace
this with method calls to the new utility methods which index the
session by the product external id.
> PP-8982 Index session by product external id

- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
Delete the payment link session after a payment has been created before
redirecting to the next_url
> PP-8982 Delete session when redirecting to payment

- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/confirm/confirm.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-link-v2/confirm.cy.test.js
- When the product has a `price`
- Do not display the `change` URL link as the user will not be allowed
to edit the price.
- Use the `product.price` when creating the payment -  ignore  the
`hidden amount form field`.
- Refactor `controller > getSummaryElements`
- Rename parameter `amount` to `sessionAmount`
- If there is a product.price, this takes priority
over the amount stored in the sesson.
- Stop checking if the `product.price` or `session amount` in multiple
places.  Check this in 1 place.
- When product has `reference_enabled=true`
- Only use the reference value from the hidden form field to create
the payment when this is enabled.
- When creating the payment
- Use the product.price if specified, otherwise use the value from
session.
- If product.reference_enabled=true, then …
> PP-8942 - Confirm page - fix bugs.

- test/cypress/integration/payment-link-v2/details-provided-in-query-params.cy.test.js
Add a Cypress tests that checks that when the reference and amount are provided as query params to the payment link, these are stored in the session and the user is then shown them on the confirm page when they click "Continue" on the payment link start page.
> PP-8966 Add Cypress test for resolving details from query params

- app/utils/captcha.js
Card scanning attacks that haven't been built for the payment link pages
generally fail to attempt the CAPTCHA challenge when it's enabled. This
will result in a POST request that doesn't have the token provided by
reCAPTCHA v2.
Currently this scenario will thrown an error which is propagated
through alerting tools. As these are generally high volume attacks this
can introduce a lot of noise.
Treat a missing token as a standard CAPTHCA fail blocking the journey,
warn for analytics but don't raise an error.
Nothing should change about the journey as requests will have been blocked
either way -- tests should still pass.
> BAU Categorise CAPTHCA token missing as warning

- app/payment-link-v2/confirm/_summary-list.njk
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/confirm/confirm.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-link-v2/amount.cy.test.js
- test/cypress/integration/payment-link-v2/confirm.cy.test.js
- Fix error with `Change` links.
- Update nunjuks files to create summary elements component correctly.
- Update `confirm.controller.js` - redirect to the `start` page on the
following situations:
- When a reference is required and it is not in the session.
- Amount is required and it is not in the session or there is no product.price.
- Update the unit tests.
> PP-8942 Confirm page fixes

- .gitignore
- app/models/Product.class.js
- app/payment-link-v2/amount/amount.njk
- app/payment-link-v2/confirm/confirm.njk
- app/payment-link-v2/reference/reference.njk
- test/cypress/integration/payment-link-v2/amount.cy.test.js
- test/fixtures/product.fixtures.js
If the payment link has an `amount_hint` specified, display it as the hint text on the amount page.
> PP-9640 Display amount hint

- app/controllers/friendly-url-redirect.controller.js
- app/controllers/pre-payment.controller.js
- app/controllers/pre-payment.controller.test.js
- app/payment-link-v2/amount/amount.controller.js
- app/payment-link-v2/amount/get-back-link-url.js
- app/payment-link-v2/amount/get-back-link-url.test.js
- app/payment-link-v2/confirm/_summary-list.njk
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/utils/payment-link-session.js
- app/payment-link-v2/utils/payment-link-session.test.js
- test/cypress/integration/payment-link-v2/details-provided-in-query-params.cy.test.js
When the reference and/or amount are provided in query params for the link, do not allow the user to change these values.
Display them on the confirm page, but without the change link.
Change the back links on pages so we skip the pages where the value has been provided by query params. The only page currently affected by this is the amount page, which shouldn't link back to the reference page if the reference was provided by the query params.
> PP-8966 Don't show change links when details provided by query params

- app/payment-link-v2/confirm/confirm.njk
- test/cypress/integration/payment-link-v2/confirm.cy.test.js
- Fix Cypress tests.
- Update to use the Cypress `within` method - to correctly search for elements
with a parent element.
- Do not have multiple IT statements within a single DESCRIBE block -
as this is the best practise and prevents testing issues.
- Add tests to check for the RECAPTCHA div element when  product.require_recaptcha=true.
> PP-8942 Confirm Page - Cypress tests

- app/payment-link-v2/amount/amount.controller.js
- app/payment-link-v2/amount/amount.controller.test.js
- app/payment-link-v2/amount/get-back-link-url.js
- app/payment-link-v2/confirm/_summary-list.njk
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/reference/get-back-link-url.js
- app/payment-link-v2/reference/reference.controller.js
- app/payment-link-v2/reference/reference.controller.test.js
- server.js
- test/cypress/integration/payment-link-v2/confirm.cy.test.js
Fix the back links to make sure that they only ever link to the confirm page when the user has clicked a change link on the confirm page.
Achieve this by adding a 'change' query parameter to the links from the confirm page and use the value of this to determine the URL for the back link.
Use the 'change' query parameter to decide whether the 'Continue' button on the reference page should redirect to the confirm page, rather than whether an amount is in the session.
These changes will allow us to add a back link to the confirm page which will allow the user to step back through the entire journey.
> PP-9476 Fix back links

- app/payment-link-v2/amount/amount.njk
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- app/payment-link-v2/confirm/confirm.njk
- app/payment-link-v2/reference/reference.njk
- test/cypress/integration/payment-link-v2/confirm.cy.test.js
- test/fixtures/product.fixtures.js
Disable whitespace changes to make reviewing easier, as indentation changed in the test file
Add a back link on the confirm page which links to the previous page in
the journey.
Also fix the styling of the back link so that it appears just below the
header banner on all pages, as per the design system guidance.
This previous page is:
The amount page, if the amount is user provided and wasn't provided by
the service in query parameters
ELSE
The reference page, if the reference is user provided and wasn't
provided by the service in query parameters
ELSE
The payment links start page.
> PP-9476 Add back link on confirm page

- app/payment-link-v2/amount/amount.njk
- app/payment-link-v2/confirm/confirm.njk
- app/payment-link-v2/reference-confirm/reference-confirm.controller.js
- app/payment-link-v2/reference-confirm/reference-confirm.controller.test.js
- app/payment-link-v2/reference-confirm/reference-confirm.njk
- app/payment-link-v2/reference/reference.controller.js
- app/payment-link-v2/reference/reference.controller.test.js
- app/payment-link-v2/reference/reference.njk
- app/routes.js
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-link-v2/reference-and-reference-confirm.cy.test.js
- Update page to use new design
- Update nunjuks file to use radio buttons
- Controller
- Update to use radio buttons
- Add validation for radio buttons
- Forward to the right page when a valid option has been selected
- Skip the amount page when editng reference, fixed price, price in query params.
- Add unit tests.
- Update Cypress tests.
> PP-9477 Reference confirm page

- app/controllers/adhoc-payment/post-index.controller.js
In app/controllers/adhoc-payment/post-index.controller.js we were not returning after calling another controller which renders a page. This meant that we could attempt to call the controller to to make a payment after rendering the reference page, which would cause an error to be thrown and then attempt to render an error page after the request had already been responded to.
I wasn't able to reproduce the circumstances this happens under, but it has been witnessed on production.
> PP-9614 Fix bug where we can respond twice to a request

- README.md
This change is to test the post-merge pact workflow, now that we are excluding some (Github Actions related) commits from the provider post-merge pact tests (see https://github.com/alphagov/pay-products/pull/931).
> BAU: Readme typo fix

- app/controllers/make-payment.controller.js
- app/errors.js
- app/middleware/error-handler.js
- app/middleware/error-handler.test.js
- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- locales/cy.json
- locales/en.json
- test/unit/controllers/adhoc-payment/post-index.controller.test.js
When an account is unable to take payments, a 403 error is returned
from Products when making a POST request to create a payment.
The 403 indicates that either:
- The account has been disabled
- The account does not have the PSP configuration added
Show a specific error message if creating a payment fails due to this.
Make this change in both `make-payment.controller.js` which is used by
the current payment link journey to create the payment and in 
`confirm.controller.js` which is used by the future payment link journey
> PP-9587 Show specific error message when account cannot take payments

- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- Removed  method deleting cookies when redirecting to the payment page
- Updated unit test to match removing cookies that delete the session when redirecting to payment page
> PP-9780 Stop deleting cookies when redirecting to payment page

- app/payment-link-v2/amount/amount.controller.js
- app/payment-link-v2/amount/amount.controller.test.js
- app/payment-link-v2/confirm/confirm.controller.js
- app/utils/currency.js
- test/unit/utils/currency.test.js
Fix IEEE 754 floating-point arithmetic errors that sneaked in when we switched to the new payment links flow.
Sometimes we need to convert an amount in pounds and pence to an amount in pence. This might seem simple: multiply it by 100. But IEEE 754 floating-point arithmetic has other ideas…
```
100.45 × 100 = 10045              😀
9.95 × 100 = 994.9999999999999  🙀
131.20 × 100 = 13119.999999999998 😬
```
Further truncation can mean we end up with an amount that’s a penny out!
Fix this by avoiding multiplication: instead treat the amount as a string and remove the decimal point from it.
(Converting an amount in pence to an amount pounds and pence by dividing by 100 is not as fraught with peril, at least for the monetary amounts we’re likely to be dealing with: see …
> PP-10028 Fix IEEE 754 floating-point arithmetic errors

- app/utils/currency.js
- test/unit/utils/currency.test.js
Fix regression introduced by commit 81cb20c2ad93ecc48bd73238bfd5da09837ab4f9 where amounts entered with only one decimal place like 0.7 and 12.5 would be wrongly interpreted as 7p and £1.25 respectively rather than the intended 70p and £12.50 respectively.
> PP-10028 Interpret amounts with only one decimal place correctly

- app/assets/sass/application.scss
Make it so that the reference on the payment link success page wraps if necessary to prepare us for a world where payment link references can be up to 255 characters.
> PP-6213 Make reference on payment link success page wrap

- app/payment-link-v2/reference/reference.controller.test.js
- app/payment-link-v2/reference/reference.njk
- app/utils/validation/form-validations.js
- app/utils/validation/form-validations.test.js
- test/cypress/integration/payment-link-v2/reference-and-reference-confirm.cy.test.js
- test/cypress/integration/payment-link-v2/welsh-reference.cy.test.js
Allow the reference number to be 255 characters long to match what our payments in general allow, rather than just 50.
Also make the field where users enter their reference full-size to accommodate such jumbo references.
Do not change the validation message just yet: this is because while this change is being released there will be a period where some servers are allowing 50 characters and some 255 and it will confuse a user if they hit a server that only allows 50 and a server that gives the 255 validation message. So we’ll just pretend it’s 50 for a little longer.
> PP-6213 Increase reference max length from 50 characters to 255

- app/payment-links/reference/reference.controller.test.js
- app/utils/validation/form-validations.js
- app/utils/validation/form-validations.test.js
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-link-v2/reference-and-reference-confirm.cy.test.js
- test/cypress/integration/payment-link-v2/welsh-reference.cy.test.js
We now allow 255 characters for references for payment links (previously 50) so update the error message.
> PP-6213 Change reference too long error message to state 255 limit

- app/assets/sass/application.scss
Use `word-wrap: break-word` in addition to `overflow-wrap: break-word` for the reference on the payment link success page to support browsers that do not support `overflow-wrap` (notably IE11).
> PP-6213 Reference on payment link success page: use word-wrap too

- package-lock.json
- package.json
Bump pay-js-commons by changing the version in the package.json, then running `npm upgrade pay-js-commons`
> ZD-5142738: Bump pay-js-commons with npm upgrade pay-js-commons

- app/payment-links/amount/amount.njk
- app/payment-links/reference/reference.njk
On the page where the user enters their payment reference, set `autocapitalize="none"` because references can have many formats and capitalising the first letter may not be appropriate.
On the page where the user enters the amount to pay, remove the `spellcheck="false"` attribute — nobody should be putting anything that can be considered a mispelling into this input so it does not matter whether or not the browser applies spelling checking.
> PP-10863 Do not autocapitalize ref and omit spellcheck for amount

- app/payment-links/amount/amount.njk
Turns out the GOV.UK Design System recommends spellcheck=false for decimal inputs, so add it back to the amount input.
This partially reverts commit 87c9a8ae7d8557b072d356b92c06c3457122df3e.
> PP-10863 Add spellcheck="false" back to amount input

- package-lock.json
- package.json
[qs](https://www.npmjs.com/package/qs) is a dependency of `request`, [which is no longer maintained](https://www.npmjs.com/package/request). So here we've added an override to get the latest compatible version of `qs`.
> PP-10951: Update qs to v6.11.1

- package-lock.json
- package.json
There has been a long running issue on `ejs`, one of the dev dependences (see https://github.com/alphagov/pay-products-ui/security/dependabot/28). Solving this should reduce noise in our dependency alerts.
The tests still pass OK when overriding `ejs` to 3.1.8.
> BAU: Resolve ejs/mountebank-formatters conflict

- package-lock.json
- package.json
- test/cypress/plugins/index.js
- Replaced request library usage in tests with Axios. This is to eventually remove the request library dependency which is not maintained anymore
> PP-10875 Remove request library usage from cypress tests

- app/clients/base/wrapper.js
- app/payment-links/confirm/confirm.controller.js
- app/payment-links/confirm/confirm.controller.test.js
- app/payment-links/reference/reference.controller.js
- app/payment-links/reference/reference.controller.test.js
- app/payment-links/utils/payment-link-session.js
- app/payment-links/utils/payment-link-session.test.js
- test/cypress/integration/payment-links/confirm.cy.js
- test/cypress/stubs/payment-stubs.js
- Displays reference page with errors if a card number is entered and products returns `CARD_NUMBER_IN_PAYMENT_LINK_REFERENCE_REJECTED` error identifier
- uses existing `potentialPANInReference` error text
> PP-11167 Handle card number in payment link reference error

- .github/dependabot.yml
See RFC: https://github.com/alphagov/pay-architecture/discussions/97
Sets NPM and Github Actions package ecosystems to security updates only.
> PP-11138: Dependabot security updates only

- .github/dependabot.yml
I got the value slightly wrong in the previous PR: https://github.com/alphagov/pay-products-ui/pull/2618.
We still want to receive updates for minor versions of Node v18.
> BAU: Ignore Node updates for v19 and above

- app/payment-links/amount/amount.controller.test.js
- app/payment/pre-payment.controller.js
- app/utils/validation/form-validations.js
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-links/amount.cy.js
For prefilled payment links, the service can set a reference and also an amount for payment links when sending the link to users.
The change involves the following:
When the user has to enter the amount manually for a non-prefilled payment link user journey, an appropriate error page with the agreed error message is displayed, if the amount is £0
Validate the amount added to the prepayment link and display an appropriate error page with the agreed error message, if the amount is £0, bypassing the confirmation page
Some further changes was done in the pay-products API, but that has be approved and released as a non-breaking change.
Knowledge of the prefilled payment link and associated validation rules.
> PP-11288 improve validation payment links v2

- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-links/details-provided-in-query-params.cy.js
- test/cypress/integration/payment-links/reference-and-reference-confirm.cy.js
Ensure products-ui & products handle reference length and content validation correctly.
https://payments-platform.atlassian.net/browse/PP-11788
Story review highlighted that apostrophes are not classed as invalid characters in payment link references. Error message for invalid characters  changed to remove apostrophes. 
This is to reflect the change made in `pay-js-commons` to allow apostrophes in pre-filled payment link references
( https://github.com/alphagov/pay-js-commons/pull/1222 )
> PP11788: Products payment creation exception review

- app/payment-links/reference/reference.controller.js
- app/payment-links/reference/reference.controller.test.js
- app/payment-links/utils/payment-link-session.js
- app/payment-links/utils/payment-link-session.test.js
- test/cypress/integration/payment-links/confirm.cy.js
When the entry in the reference field of a payment link looks like a card number and fails the check and the user is returned to the reference page, the reference field should be empty.
- Remove reference from session cookie if the field tests positive for a card number
- Empty reference field
- Update cypress test
> PP-11340 Clear reference field after positive card number check

- app/clients/adminusers/find-service.pact.test.js
- app/clients/products/payment.create.pact.test.js
- app/clients/products/payment.get-by-gateway-account-id-and-reference.pact.test.js
- app/clients/products/payment.get-by-payment-external-id.pact.test.js
- app/clients/products/payment.get-by-product-external-id.pact.test.js
- app/clients/products/product.get-by-gateway-account-id.pact.test.js
- app/clients/products/product.get-by-product-external-id.pact.test.js
- app/clients/products/product.get-by-product-path.pact.test.js
- bin/publish-pacts.js
- package-lock.json
- package.json
- Upgrades pact JS to the latest
- Replace pact-node library with pact-core
- Call verify() after pact tests which checks the expected interactions have happened.
> PP-11918 Upgrade pact library

- app/middleware/error-handler.js
- app/middleware/error-handler.test.js
- app/views/error.njk
- app/views/prefilled-link-error.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-links/details-provided-in-query-params.cy.js
PP-11978  Improve error message associated with validation of amount on pre-filled payment links
Summary of changes:
- Amend page title and page heading for prefilled payment link problems
- Reference new payment link template
- Update associated unit test to reflect changes
- Update Cypress integration test
- Remove logic to test for pre-filledpayment link specific message from common error template
- Add template dedicated for pre-filled payment link problems
Screenshots
The screen shots below can also be found in the [jira ticket PP-11978](https://payments-platform.atlassian.net/browse/PP-11978)
> PP-11978 improve pre-filled payment link error message

- app/middleware/error-handler.js
- app/payment/pre-payment.controller.js
- app/payment/pre-payment.controller.test.js
With @JFSGDS 
- No longer throw exceptions when an invalid pre-filled amount or reference.
- Error are now sent to he error handler using the next function.
- Previously, the errors were logging errors in Sentry and we do not want that.  As these errors are user errors.
> Pp 11978 suppress prepayment link error in sentry

- app/payment/pre-payment.controller.js
- app/payment/pre-payment.controller.test.js
PP-11978 Improve error message associated with validation of amount on pre-filled payment links
https://payments-platform.atlassian.net/browse/PP-11978
Summary of changes
- Render pre-filled payment link error page and generate ‘info’ log message from within pre-payment controller instead of using 'error-handler.js' . This is in order to prevent related error messages being displayed in Sentry logs.
- Update associated unit tests to reflect the above change.
> PP-11978 - Render pre-filled error page from within pre-payment controller

- app/errors.js
- app/middleware/error-handler.js
- app/middleware/error-handler.test.js
- app/payment/pre-payment.controller.js
- app/payment/pre-payment.controller.test.js
PP-11978 Prevent pre-filled payment link errors displaying in Sentry.
https://payments-platform.atlassian.net/browse/PP-11978
Summary of changes
- Remove redundant error classes as error page now handled in pre-payment controller.
- Reword log messages for pre-filled payment link errors as error classes no longer available. For example:
`"message":"Invalid prefilled reference error handled: Invalid reference: <>. Rendering problem page"`
`"message":"Invalid prefilled amount error handled: Invalid amount: not-valid. Rendering problem page"`
- Set new error page rendered status to 400.
- Update unit tests to reflect the above.
> PP 11978 Remove redundant pre-filled payment link error classes

- app/payment/payment-complete.controller.test.js
- app/payment/payment-status.controller.js
Removing unnecessary spaces from the payment reference number.
It is impacting users and is also inconsistent with the usage of references in other places (email, admin tool). Users were copying the reference with spaces. However, service teams won’t be able to find transactions if searching by the same (reference with spaces) as we don’t store spaces in the database or anywhere.
Before:
After:
> PP-12064 Remove beautify method so references do not have spaces

- README.md
- config/server.js
Bind to 127.0.0.1 by default instead of 0.0.0.0 and allow override with BIND_HOST env var.
You can see this works, on master:
*  On master run `npm run start:dev`
* Then netstat:
```
$ netstat -anl | grep 3000
tcp46      0      0  *.3000                                        *.*                                           LISTEN
```
* Switch to this branch, then `npm run start:dev`
* Then netstat:
```
$ netstat -anl | grep 3000
tcp4       0      0  127.0.0.1.3000                                *.*                                           LISTEN
```
* Now `BIND_HOST=0.0.0.0 npm run start:dev`
* A final netstat to prove the override works
```
$ netstat -anl | grep 3000
tcp4       0      0  *.3000                                        *.*                                           LISTEN
``` …
> PP-13145: Accept BIND_HOST env var and default to localhost

- package-lock.json
- package.json
Changes to pay-js-commons had broken custom branding. Revert changes.
> BAU roll pay-js-commons to revert previous changes

- cypress.config.js
- package-lock.json
- package.json
- test/cypress/plugins/index.js
- test/cypress/stubs/service-stubs.js
- test/cypress/stubs/stub-builder.js
- test/cypress/support/index.js
As Mountebank is being deprecated we're moving onto our own `run-amock` project. which is a drop-in replacement for the functionality we've been using from Mountebank.
(related to https://github.com/alphagov/pay-frontend/pull/3913 and https://github.com/alphagov/pay-selfservice/pull/4287)
Also Removing verifyStubs as it's never used, each test can specify that the stubs inside it should be verified but no individual test uses this functionality.
> PP-13235: Using a mountebank replacement.

- package-lock.json
- package.json
Using the latest version of `run-amock` which uses case-sensitive query strings as we no longer have to maintain feature-compatibility with Mountebank.
> PP-13234: Using latest run-amock

- package-lock.json
- package.json
Dependency upgrades for:
- `express` (to bring in a fix for `path-to-regexp` v0.1.12 - see [express changelog](https://github.com/expressjs/express/releases/tag/4.21.2))
- `cross-spawn` (via npm audit fix)
- `micromatch`(via npm audit fix)
- `nanoid` (via npm audit fix)
- `pact-core` (via npm audit fix)
-  other occurrences of `path-to-regexp` (via npm audit fix)
Dependabot was unable to create pull requests for these upgrades automatically.
> PP-13422: Upgrade express to v4.21.2

- Gruntfile.js
- package-lock.json
- package.json
- No longer required as we no longer support the old browsers which required this.
> PP-12475 Remove HTML5 shiv NPM module and references

- app/views/includes/custom.njk
- test/cypress/integration/payment-links/start.cy.js
- When testing the new branding, we identified that it caused a couple of bugs with custom branding.
- This ticket is to update custom branding tests to pick up these issues.
- This ensures that when the new branding is implemented - these tests will fail unless the bugs are fixed.
- The tests have been updated to check the following:
- Make sure the bottom border is of the container is visible.
- Check background colour of the logo's container.
Fails if the bottom border is not visible:
Fails if the background of the logo is not transparent
> PP-14109 Update custom branding Cypress tests

- .github/workflows/_run-tests.yml
- Add the step to run the Cypress rebranding tests to GHA.
> PP-13896 Add Cypress rebrand tests to Github actions

- app/models/Service.class.js
- app/models/Service.class.test.js
- app/views/layout.njk
- test/cypress/integration/payment-links/footer.test.cy.js
- test/fixtures/service.fixtures.js
- Update service class to save merchant address in the right format when it comes back from the backend.
- The address was not being shown in the footer because it was not being saving in the right format in the service class.
- Update tests and stubs.
- The country is currently being shown as 2 digit ISO code.  This will be updated in a future PR to show the full country name.
> PP-14242 Footer bug fix - not showing address

- app/models/Service.class.js
- app/models/Service.class.test.js
- package-lock.json
- package.json
- test/cypress/integration/payment-links/footer.test.cy.js
- Use function from pay-js-commons to convert country code to full country name.
> PP-14242 Footer - display full country name
