- docker-startup.sh
- Added missing docker-startup file for msl to start this service
> PP-2611 Add Node js app to local dev

- Jenkinsfile
Added Jenkinsfile for this empty repo. Should be enough to build and push a container to Docker Hub.
> PP-2611 Added Jenkinsfile with no deploy and no end2end

- Jenkinsfile
Build pipeline is ready so triggering deploy upon successful build
> PP-2610 adding deploy step

- .dockerignore
- Dockerfile
- build-local.sh
- docker/build_and_test.Dockerfile
- Copying of docker updates from pay-selfservice to pay-products-ui
- Improves local build times by moving npm install step inside container build
> Fix docker local build

- app/controllers/demo_payment/payment_complete_controller.js
- app/models/Payment.class.js
- app/models/Product.class.js
- test/fixtures/product_fixtures.js
- test/unit/controllers/demo_payment/payment_complete_controller_test.js
- update payment model
- update payment fixture
- update tests
> PP-2655 Fix payment model to include govuk_status

- app/views/confirm_demo_payment/success.html
New id attribute facilitating the selection of `Go to transactions` button in end to end tests.
> PP-2893 Id attribute for end to end test

- app/assets/sass/modules/demo-confirmation.scss
- Update the sass used on the example image used on the failure and success pages so that it doesn't have a black border
> PP-2727 Update the sass used on the example image used on the failure and success pages

- .snyk
- Ignore Snyk timespan report - https://snyk.io/vuln/npm:timespan:20170907
- Update serve-favicon to latest version
Related story: https://payments-platform.atlassian.net/browse/PP-2687
Please see commits for more information
> PP-2687 Snyk issues

- Dockerfile
- package.json
- remove sleep npm dependency as it is not used
- remove dockerfile deps used to build sleep
> PP-3004 remove sleep

- Jenkinsfile
Also making sure it runs on the PROMOTED_ENV url.
> PP-2996 enable smoke tests on AWS deploy

- README.md
Mainly to add a new commit id so that (hopefully) will resolve the jenkins master branch issue.
> PP-2996 Update readme

- app/services/clients/products_client.js
- config/index.js
- test/fixtures/product_fixtures.js
- test/test.env
- test/unit/client/product_client/payment/create_test.js
- test/unit/client/product_client/payment/get_by_payment_external_id_test.js
- test/unit/client/product_client/payment/get_by_product_external_id_test.js
- test/unit/client/product_client/product/create_test.js
- test/unit/client/product_client/product/disable_test.js
- test/unit/client/product_client/product/get_by_gateway_account_id_test.js
- test/unit/client/product_client/product/get_by_product_external_id_test.js
- remove PRODUCTS_API_TOKEN and all usage of it. It is no longer used.
> PP-3204 remove usage of PRODUCTS_API_TOKEN

- app/browsered/field-validation-checks.js
- test/unit/browsered/field_validation_checks_test.js
- fix amount validation (error when amount is above £100.000 and not when equal or above)
> PP-3305 Fix amount validation for payments

- app/controllers/adhoc_payment/get_amount_controller.js
- app/controllers/adhoc_payment/submit_amount_controller.js
- app/views/adhoc-payment/amount.njk
- test/fixtures/product_fixtures.js
- test/unit/controllers/adhoc_payment/get_amount_controller_test.js
- test/unit/controllers/adhoc_payment/submit_amount_controller_test.js
- Made the `get_amount_controller` to display payment amount or input payment amount based on the availability of `product.price`
- Changed `submit_amount_controller` to proceed to payment based on the similar check by using either the product.price or input amount.
> PP-3239 Fixed price ADHOC journey

- run-with-chamber.sh
This is what gets secrets when running under ECS
> PP-3252 added run-with-chamber.sh for ECS running

- app/views/includes/footer-categories.njk
- config/index.js
- docker/build_and_test.Dockerfile
- test/unit/controllers/demo_payment/payment_failed_test.js
- test/unit/controllers/demo_payment/payment_success_test.js
Update all referenced links to new url
Added npm-shrinkwrap.json to build docker file as sntp has been upgraded and we need to pin it our version
solo @belindac
> PP-3379 Change documentation link in header and footer

- manifest.yml
As we aren't deploying to PAAS anymore.
> PP-3126: Remove manifest.yml

- app/views/includes/head.njk
- server.js
- Added boilerplate stuff to server.js
- Added GA javascript to template
- Passing service name to GA as dimension 1
> PP-3394 - Adding analytics to Products UI

- app/controllers/product_reference/get_product_reference_controller.js
- app/views/reference/index.njk
- test/unit/controllers/payment_reference/get_product_reference_controller_test.js
- test/unit/controllers/pre_payment_controller_test.js
- Updated page to include extra `label` and `hint` if available
- Updated tests
> PP-3726 Add fields for page reference input

- app/controllers/adhoc_payment/get_index_controller.js
- app/controllers/product_reference/post_product_reference_controller.js
- app/views/adhoc-payment/index.njk
- app/views/reference/index.njk
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
- Added field length validation to 255
- Updated error messages
- Hide/display product name and description in ADHOC payment pages
> PP-3726 Updated error messages

- app/browsered/field-validation-checks.js
- app/browsered/field-validation.js
- app/views/reference/index.njk
need to add NAXSI rules for these too
> PP-3726 - Add validation to stop people using nasty chars

- app/controllers/product_reference/post_product_reference_controller.js
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
- remove the constraint of unique user entered reference number
> PP-3886 Remove unique constrain for user entered reference

- app/controllers/payment_status_controller.js
- remove the slicing of reference number on the success page if user entered reference is enabled (pass through)
> PP-3836 Remove beautification of reference number

- app/routes.js
#94 raised via alphagov so the pr builder works
> PP-3133: Route unknown pages to gov.uk/404

- server.js
- test/integration/404_tests.js
- Fixes 404 vs static assets
- Adds tests
solo @tlwr
> PP-3133 tests fixes

- Gruntfile.js
- app/browsered.js
- app/views/layout.njk
- package-lock.json
- package.json
- server.js
- remove jQuery
- apply Babel after browserify
- apply Nodemon excludes
- set up live reload for client-side JS
> PP-4406 - Apply learnings to streamline JS

- app/views/confirm_demo_payment/failed.njk
- app/views/confirm_demo_payment/success.njk
and so appearing with defaut link styles
> BAU - these links were missing link class 

- app/controllers/adhoc_payment/get_index_controller.js
- app/controllers/payment_status_controller.js
- app/controllers/product_reference/get_product_reference_controller.js
- app/middleware/resolve_payment_and_product.js
- app/middleware/resolve_product.js
- app/services/clients/adminusers_client.js
- test/fixtures/service_fixtures.js
- test/unit/controllers/adhoc_payment/get_index_controller_test.js
- test/unit/controllers/adhoc_payment/get_index_controller_unit_test.js
- test/unit/controllers/adhoc_payment/post_index_controller_test.js
- test/unit/controllers/payment_complete_controller_test.js
- test/unit/controllers/payment_reference/get_product_reference_controller_test.js
- test/unit/controllers/payment_reference/post_product_reference_controller_test.js
- test/unit/controllers/pre_payment_controller_test.js
- test/unit/middleware/resolve_payment_and_product_test.js
- test/unit/middleware/resolve_product_test.js
- refactor middleware to get service object from adminusers
- refactor controllers to use the service object
- refactor relevant tests
> PP-4924 refactor to use service object for service name

- app/services/clients/adminusers_client.js
- test/unit/client/adminusers_client/find_service_test.js
> PP-4924 Correct copy-paste mistakes

- app/views/reference/index.njk
- correct the spelling mistake
> PP-4924 Correct spelling mistake

- Gruntfile.js
- app/controllers/adhoc_payment/get_index_controller.js
- app/controllers/product_reference/get_product_reference_controller.js
- app/views/adhoc-payment/index.njk
- app/views/includes/custom.njk
- app/views/includes/head.njk
- app/views/layout.njk
- app/views/reference/index.njk
- package-lock.json
- package.json
- server.js
- Use same nunjucks markup that makes custom branding work in frontend
- Get custom branding sass and logos from pay-js-commons
> PP-4924 - custom branded templates

- package-lock.json
- package.json
> PP-4904 - lint on pre commit hook

- Jenkinsfile
- Have not enabled checking pact compatibility yet
> PP-5005 Run contract tests as part of build

- app/controllers/adhoc_payment/get_index_controller.js
- app/controllers/payment_status_controller.js
- app/controllers/product_reference/get_product_reference_controller.js
- app/middleware/resolve_payment_and_product.js
- app/middleware/resolve_product.js
- app/views/adhoc-payment/index.njk
- app/views/includes/custom.njk
- app/views/includes/head.njk
- app/views/layout.njk
- app/views/reference/index.njk
- Set service in locals rather than passing it into template in
individual controllers so that the service name and custom branding
can be shown on error pages
- Resolve service name in correct language variant in layout.njk
> PP-5007 Resolve the language variant of the service name

- test/unit/controllers/adhoc_payment/get_index_controller_test.js
- test/unit/controllers/payment_complete_controller_test.js
- test/unit/controllers/payment_reference/get_product_reference_controller_test.js
Add some basic integration text to ensure we are resolving the language correctly on the reference, amount and confirmation pages
> PP-5007 Add tests that language is resolved correctly

- app/controllers/adhoc_payment/post_index_controller.js
Related to https://github.com/alphagov/pay-products-ui/pull/377
> PP-5314 - Needed to add this in two places

- package-lock.json
- package.json
- Bumps pay-js-commons version from 2.7.0 to 2.9.0
> Bump pay-js-commons to 2.9.0

- package-lock.json
- package.json
- Bumps pay-js-commons to 2.10.0 from 2.9.0
> Bump pay-js-commons to 2.10.0

- app/assets/sass/application.scss
- app/views/adhoc-payment/index.njk
- app/views/confirm_demo_payment/failed.njk
- app/views/confirm_demo_payment/success.njk
- app/views/layout.njk
- app/views/reference/index.njk
- package-lock.json
- package.json
- server.js
Updated all templates to meet breaking changes as part of 3.0.0 release which are all detailed here — https://github.com/alphagov/govuk-frontend/releases/tag/v3.0.0
This 3.0 release includes numerous accessibility updates but most visually prominent is the all new colour scheme - https://designnotes.blog.gov.uk/2019/07/29/weve-made-the-gov-uk-design-system-more-accessible/
> PP-5560 - govuk-frontend 3.0 upgrade

- app/views/includes/head.njk
See See https://docs.google.com/document/d/1Scq-axCUknouQhKkf5ppqcqljeWSo62njL4p9qGcIjo/edit#
> Send analytics to cross-gov too

- README.md
This still needs a lot of work, but at least we have a list now.
> Enumerate key environment variables in the README

- app/views/layout.njk
Must be deployed after alphagov/pay-product-page#162
> PP-5653 - add a link to statement in the footer

- app/controllers/static_controller.js
> BAU - error message is a template variable

- app/controllers/make_payment_controller.js
- app/controllers/static_controller.js
- app/utils/response.js
These do not constitute a failure of something important in the running of
products-ui.
> PP-5809: Downgrade log level to INFO

- test/fixtures/service_fixtures.js
Remove random data from pacts which was causing pact broker to think
the pact has changed for every release.
> BAU Remove randomness from adminusers pacts

- package-lock.json
- package.json
Changes formatting of logo for Torbay and South Devon NHS Foundation
Trust
> ZD-3873417 Bump pay-js-commons to 2.20.1

- .travis.yml
Adds a simple .travis.yml build configuration for running CI node build tasks.
> Add .travis.yml build configuration

- package-lock.json
- package.json
Reverts alphagov/pay-products-ui#926
This change is breaking master build
> Revert "build(deps-dev): bump envfile from 5.2.0 to 6.12.0"

- package-lock.json
- package.json
For Planning and Building Services Edinburgh.
> zd4186401: Custom branding

- package-lock.json
- package.json
This is for right-aligning the logo. see https://github.com/alphagov/pay-js-commons/pull/421
> zd4195581: Custom branding for Adur & Worthing Council

- README.md
We don't have Cypress tests for products-ui
> PP-7965 Minor README changes

- Dockerfile
Wasn't using the linux/amd64 version.
> PP-8306 Fix base docker image version

- package-lock.json
- update known vulnerabilities:
upgrade node-fetch to version 2.6.1
upgrade minimist to version 0.2.1, 1.2.3 or higher
> PP-8427 address vulnerabilities

- package-lock.json
- package.json
- test/fixtures/pact-base.js
- test/unit/client/adminusers.client/find-service.pact.test.js
- test/unit/client/product.client/payment/create.pact.test.js
- test/unit/client/product.client/payment/get-by-gateway-account-id-and-reference.pact.test.js
- test/unit/client/product.client/payment/get-by-payment-external-id.pact.test.js
- test/unit/client/product.client/payment/get-by-product-external-id.pact.test.js
- test/unit/client/product.client/product/create.pact.test.js
- test/unit/client/product.client/product/delete.pact.test.js
- test/unit/client/product.client/product/disable.pact.test.js
- test/unit/client/product.client/product/get-by-gateway-account-id.pact.test.js
- test/unit/client/product.client/product/get-by-product-external-id.pact.test.js
- test/unit/client/product.client/product/get-by-product-path.pact.test.js
- removes pact@4.3.2 package which is deprecated https://www.npmjs.com/package/pact
- Added new dependency of pact `@pact-foundation/pact`
- and related changes
> PP-8575 Update pact dependency

- package-lock.json
- Updates `tar` version to latest - https://nodejs.org/en/blog/vulnerability/aug-2021-security-releases2/
> PP-8575 Update `tar` to latest version

- app/errors.js
- app/middleware/error-handler.js
- app/middleware/error-handler.test.js
- app/paths.js
- app/payment-link-v2/amount/amount.njk
- app/payment-link-v2/amount/get-index.controller.js
- app/payment-link-v2/amount/get-index.controller.test.js
- app/payment-link-v2/amount/index.js
- app/payment-link-v2/amount/post-index.controller.js
- app/routes.js
- app/utils/replace-params-in-path.js
- app/views/404.njk
- locales/cy.json
- locales/en.json
- server.js
- Create new Amount page - this page will not be active initially until it is tested.
- Add new URLs to paths.js
- Add `get` and `post` controller.
- Add tests
- Update the error middleware
- Add code to show a 404 error.
co-authored: @iqbalgds @0atman
> PP-8941 - New Payment Link journey - Adding the amount page

- locales/cy.json
- locales/en.json
- Change error message from `enter a` to `enter a valid`
- Mean we do not have to worry using `a` or `an`
> PP-8940 Reference - update error messeage

- test/cypress/stubs/products-stubs.js
- test/cypress/stubs/service-stubs.js
- test/cypress/stubs/stub-builder.js
- Add stub builder - copy of the version found in Self Service.
- Add stubs for `products` and `services`.
> PP-8970 Cypress tests - add stubs.

- .github/workflows/run-tests.yml
- This runs tests tests in parallel.
- Makes it consistent with other Pay repos.
> PP-8970 Update Github actions to make the same as Self service.

- Jenkinsfile
- Use the Self service > Jenkins > Cypress settings as a template.
- Update Products-UI Jenkins with these settings.
- Update the Cypress version to 9.5.0
> PP-8970 Jenkins > Add Cypress

- app/payment-link-v2/amount/index.js
- app/payment-link-v2/reference-confirm/reference-confirm.controller.js
- app/payment-link-v2/reference-confirm/reference-confirm.controller.test.js
- app/payment-link-v2/reference-confirm/reference-confirm.njk
- locales/cy.json
- locales/en.json
- Update Nunjucks file with new data and design.
- Update controller to provide data for new design.
- Add unit test.
- Remove old and unused file - index.js.
> PP-8978 Reference confirm updates

- app/controllers/pre-payment.controller.js
- app/controllers/pre-payment.controller.test.js
- Accept query parameters 'reference' and 'amount'. If they are present, set them in the payment link session.
- When the user clicks 'Continue' on the payment link start page, take them to the next page where a value has not already been provided. If both reference and amount have been provided or are fixed for the payment link, 'Continue' takes them to the confirm page.
- If either the reference or amount is not valid, ignore the query parameter values provided and ask the user to enter them in the UI.
> PP-8966 Accept query parameters for reference and amount

- app/payment-link-v2/confirm/confirm.controller.js
- app/payment-link-v2/confirm/confirm.controller.test.js
- Pass the recaptcha flag to the `confirm.njk` page.
- Update unit tests.
- Cypress tests will be updated in another PR
> PP-8942 Confirm page - fix recaptcha bugs

- env-map.yml
> BAU: remove env-map as it was used by PaaS

- app/payment-link-v2/reference-confirm/reference-confirm.controller.js
- app/payment-link-v2/reference-confirm/reference-confirm.controller.test.js
- app/payment-link-v2/reference-confirm/reference-confirm.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-link-v2/reference-and-reference-confirm.cy.test.js
- Update heading to include reference label.
- Update nunjuks file
- Update unit and Cypress tests.
- Show a 404 if there is no reference in the session.
- Update controller
- Add new test
- Update error message
- Update text and make it include the reference label.
- Update unit and Cypress tests.
> PP-9477 Reference confirm page - fix bugs.

- .github/dependabot.yml
Update dependabot config to include docker
> PP-9754: Add dockerfile to dependabot

- locales/cy.json
Updated cy.json with the latest Welsh translations for the updated payment
link pages.
> PP-9453-Payment link Welsh translations

- app/payment-link-v2/amount/amount.njk
- app/payment-link-v2/confirm/confirm.njk
- app/payment-link-v2/reference-confirm/reference-confirm.njk
- app/payment-link-v2/reference/reference.njk
- app/views/macros/error-summary.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-link-v2/reference-and-reference-confirm.cy.test.js
- test/cypress/integration/payment-link-v2/welsh-reference.cy.test.js
- Added a Welsh Cypress test file for reference page
- Updated the English Cypress test for reference page to check
error-summary heading.
- Updated macros function and added titleText parameter to accept
translated title text.
- Updated existing cypress test to use the updated  error-summary macro.
> PP-9453 Welsh translations - Cypress tests + bug fixes

- package-lock.json
- package.json
##WHAT
- Removed and uninstalled husky package.json files.
>  PP-8776 Removing husky from app

- package-lock.json
- package.json
> BAU bump pay-js-commons -> 3.6.2

- app/browsered/field-validation-checks.js
- app/utils/validation/form-validations.js
- refactor lcoal validations to use pay-js-commons field validations
> PP-1955 refactor validations to use pay-js-commons

- app/browsered/field-validation-checks.js
- app/browsered/field-validation-checks.test.js
- remove unused function from code
> PP-9955 remove unused functions from old code

- package-lock.json
- package.json
- bump pay-js-commons that contains custom branding for Neath Port Talbot Council
> ZD-5110969 bump pay-js-commons to 3.8.2

- package-lock.json
- package.json
Pulls in additional custom branding updates.
> ZD-5142783: Bump pay-js-commons to 3.8.5

- .github/workflows/post-merge.yml
- .github/workflows/run-tests.yml
Located and replaced all usages of set-output commands in our workflows.
> PP-10675:replaced all usages of set-output

- package-lock.json
- package.json
> ZD-5313486 wealden custom branding

- package-lock.json
- package.json
This contains custom branding for Runnymede Borough Council.
> ZD-532159 Update to pay-js-commons version 3.8.10

- package-lock.json
- package.json
- Bump pay-js-commons to 3.10.0
> zd-5365276-bump-js-commons-to-3.10.0

- package-lock.json
- package.json
This version contains custom branding for Oswestry Town Council.
> ZD-5424472 Update Pay JS Commons version to 3.11.2

- package-lock.json
- package.json
> PP-11548: Update pay-js-metrics

- package-lock.json
- package.json
- Pick up the latest custom branding styling.
> PP-11040 Bump pay-js-commons to 4.0.5

- app/middleware/error-handler.js
- app/middleware/error-handler.test.js
- app/views/error.njk
- locales/cy.json
- locales/en.json
- test/cypress/integration/payment-links/details-provided-in-query-params.cy.js
Ensure products-ui & products handle reference length validation correctly.
https://payments-platform.atlassian.net/browse/PP-11788
- Add messages for invalid amount and invalid reference on pre-filled links to be passed to error template.
- Update unit, integration and end-to-end tests for invalid amount and reference on pre-filled links
- Create English and Welsh versions of error text
> PP-11788 Products: PaymentCreationException

- package-lock.json
- package.json
Bump `pay-js-commons` version to 4.0.9. This bump includes the custom branding for Penzance Council.
> ZD-5569361 bump pay-js-commons version

- package-lock.json
- package.json
Includes custom branding for the UK Atomic Energy Authority.
> ZD-5598666 Upgrade to Pay JS commons 4.0.11

- package-lock.json
- package.json
To release service custom branding
> ZD-5604893 Bump pay-js-commons to version 4.0.13

- README.md
👋🏻 I was being nosey and noticed this link was broken, so I fixed it.
> Update broken link to Pay team manual

- package-lock.json
- package.json
Update to pay-js-commons 5.0.3, which includes custom branding for University Hospital Southampton NHS Foundation Trust.
> ZD-5842004 Update to pay-js-commons 5.0.3

- package-lock.json
- package.json
- Pay-js-commons has been updated with the latest changes of Axios base client.
- The new changes do not affect this repository directly, but want to update the version so that it is aligned with the other reporistories.
> PP-12659 Bump pay-js-commons

- app/utils/cookie.js
- app/utils/cookie.test.js
Implements `[RFC] SameSite attribute for cookies`
add SameSite=Lax to:
- session
> PP-13012 add SameSite Lax to cookies

- app/utils/captcha.js
- app/utils/captcha.test.js
- migrate reCaptcha Enterprise to `v1`
> PP-13110 migrate recaptcha enterprise to v1

- app/utils/cookie.js
- app/utils/cookie.test.js
- wrong variable casing used. Fix casing.
> PP-13012 fix SameSite session cookie

- package-lock.json
- package.json
update pay-js-commons to 6.0.14
> ZD-5942688 update pay-js-commons

- app/clients/base/request-context.js
- app/clients/base/request-context.test.js
- Update instance where CORRELATION_ID const was used instead of CORRELATION_HEADER.
- Some minor code cleanup.
> PP-13232 Fix correlation id bug

- package-lock.json
- package.json
- Needed for Custom branding
- https://govuk.zendesk.com/agent/tickets/5983194
>  ZD-5983194 Update-pay-js-commons

- package-lock.json
- package.json
- Required for NHS Greater Manchester
> ZD-601647 Bump pay-js-commons to pick up new custom branding.

- package-lock.json
- package.json
This should be compatible with the existing tests.
Related PRs:
The change in Run Amock: https://github.com/alphagov/pay-run-amock/pull/16
Updates to other projects:
https://github.com/alphagov/pay-frontend/pull/3950
https://github.com/alphagov/pay-selfservice/pull/4439
> PP-13557: Using the latest release of Run Amock

- package-lock.json
- package.json
- Required for custom branding
- Scottish gov payments
- Health Services Safety Investigations Body (HSSIB)
> ZD-6032459 & ZD-6017555 - bump pay js commons

- package-lock.json
- package.json
- point to latest pay-js-commons to pick up image and scss for custom branding request.
> ZD-6053016 point to latest pay-js-commons

- package-lock.json
- package.json
https://govuk.zendesk.com/agent/tickets/6061195
> ZD-6061195 Use latest Pay-JS-commons

- package-lock.json
- package.json
Updating to use latest pay-js-commons after custom branding update.
> Update to use latest js commons

- app/routes.js
In the previous PR a mistake was made.
Move middleware call _before_ controller call in routes.
> PP-13896 refactor routes

- app/models/Service.class.js
- app/views/layout.njk
- package-lock.json
- package.json
- test/cypress/integration/payment-links/footer.test.cy.js
- test/cypress/integration/payment-links/start.cy.js
- test/cypress/stubs/service-stubs.js
- test/fixtures/service.fixtures.js
- We want to change the Nunjuks code to use the design system Nunjuks Macro. This will allow us to pick up new changes from the design system automatically. This will also make it easier to make the new brand changes.
- Updated the footer to use the Nunjucks macro.
- Updated the footer as per new design
-  Added new cypress test to check the footer
Percy build:
https://percy.io/55ba5e1a/web/pay-products-li/builds/40934633/changed/2198160808?aiToggleEnabled=true&browser=chrome&browser_ids=64&group_snapshots_by=similar_diff&subcategories=unreviewed%2Cchanges_requested&test_case_ids=&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280
> PP-14071 update footer design

- package-lock.json
- package.json
Bump pay-js-commons to 7.0.6 for custom branding
> ZD-6148303 bump pay-js-commons

- package-lock.json
- package.json
Updating pay-js-commons to version 7.0.14
> PP-13427 update pay-js-commons

- package-lock.json
- package.json
Includes custom branding for Coedffranc Town Council.
> ZD-6190751 Upgrade to Pay JS Commons 7.0.17

- package-lock.json
- package.json
New version of pay-js-commons.
> ZD-6208926 Custom Branding for Surrey County Council
